language: java
jdk: oraclejdk8
script: ./gradlew assemble test
sudo: required

before_install:
     - chmod +x gradlew

cache:
 directories:
  — $HOME/.gradle

deploy:
  provider: releases
  skip_cleanup: true
  api_key:"37ce05f6380795dfe86edf7acb079e06ce028623"
  file_glob: true
#  file: SmartTomcat*.jar
  file: build/libs/SmartTomcat*.jar
  on:
    tags: true
