language: java
jdk: oraclejdk8
script: ./gradlew assemble test
sudo: required

before_install:
     - chmod +x gradlew

cache:
 directories:
  — $HOME/.gradle

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qCdcXjTabHaOvEMnVRRHB9hl3w39hYQA+obyxVuZje/oCsKQ1nEkvO31ZZ3jQp3pBd6LRi7eba3h5UozUnoaevPcM5EjJBhhhkzDdtCveLg9FBPYWGxc8tcbdmpB+IqijI5dn7MjiIERMcUbkT6dbCVtiFUp2EqkK4JbyaRHbDuCvztY2kpAvSJ8AE1v+Rl671Z29T9VSH06sVY9gbISE1+41BUfpLaI2qwkCOvtHJhvnuHnRNIiJw2WV4TM1kMnSIjIwOCmK6/tvW3giiaEb72XqOtKhr0sFZ5rhDiKRSQmZ8raEFFSjWi4G+ULPxljomlJtnLrw+Cm2cre83aPFDvKrcO5RuKZEcSBVHFIg+8ha2y+DJH8+CsDKa8kfMakkzBjcppRyPkb6PLiNAL0cP8Fp8U69/0UxVe5x4fO+2vLieRHPS5pey3rJIT1BKMyBoo0BKsbrfSMfzqd5Y6xL6JmyOM1fU7wOtMZSnDJbkK63Fs2ra87tVtUlifzaXdEpG2JZktNS48wEiZyXMgB88UAg32jsJqUF8zEBaHMjdMbIkRPm5otrNOIgAL2tfH4gSbA7I9mtFE4f5eP+mS6HejSm4fdsNT1DzRQf42WtdZ/mCju0fHF/qPz6qVABRFFma4hbmq7rDCcJSCALu4IcMZzqdoB5n0BJT/SknFiMEs=
  file_glob: true
  file: build/libs/SmartTomcat*.jar
  on:
    tags: true
