name: Gradle Build

on:
  push:    
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload to release
        uses: zengkid/SmartTomcat@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: build/libs/SmartTomcat-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
